export type Board = {
    id: string,
    name: string,
}

export type Prefs = {
    permissionLevel: string,
    hideVotes: boolean,
    voting: string,
    comments: string,
    invitations: string,
    selfJoin: boolean,
    cardCovers: boolean,
    isTemplate: boolean,
    cardAging: string,
    calendarFeedEnabled: boolean,
    hiddenPluginBoardButtons?: Array<any>,
    switcherViews?: Array<any>,
    background: string,
    backgroundColor: null,
    backgroundImage: string,
    backgroundImageScaled: Array<any>,
    backgroundTile: boolean,
    backgroundBrightness: string,
    backgroundBottomColor: string,
    backgroundTopColor: string,
    canBePublic: boolean,
    canBeEnterprise: boolean,
    canBeOrg: boolean,
    canBePrivate: boolean,
    canInvite: boolean
}

export type LabelNames = {
    green: string,
    yellow: string,
    orange: string,
    red: string,
    purple: string,
    blue: string,
    sky: string,
    lime: string,
    pink: string,
    black: string,
    green_dark: string,
    yellow_dark: string,
    orange_dark: string,
    red_dark: string,
    purple_dark: string,
    blue_dark: string,
    sky_dark: string,
    lime_dark: string,
    pink_dark: string,
    black_dark: string,
    green_light: string,
    yellow_light: string,
    orange_light: string,
    red_light: string,
    purple_light: string,
    blue_light: string,
    sky_light: string,
    lime_light: string,
    pink_light: string,
    black_light: string
}